### PR TITLE
Add BOSH support

### PR DESCRIPTION
**Pull request by paweldomas**
This PR adds BOSH support to Smack 3 using jbosh library.

- "jbosh" is fetched through the jitpack.io repo in order to get the version we need (06ee5a43a0)
- for ant build there is a binary jar of this version placed in merge dir: smack/tags/smack_3_2_2/build/merge/jbosh-06ee5a43a0.jar
- in order to add new BOSH connection class there was AbstractConnection class extracted from XMPPConnection. PacketReader and PacketWriter were also modified, so that their logic can be shared between TCP and BOSH implementation
- getSocket method was added to Connection in order to be able to use Connection class in Jitsi without checking for "is instance of XMPPConnection"
- during the PR review it is important to make sure that the behaviour of XMPPConnection class remained the same after "Extract AbstractConnection class" https://github.com/jitsi/smack_3_2_2/commit/3a585babbab6d46f957b6260840f61f622b3169a
- this PR bumps the version to 3.2.2-jitsi-2-SNAPSHOT

### CODE REVIEW

**Comment by ibauersachs** [comment]
Instead of fiddling with Smack 3.2, can't we channel resources into finally upgrading to **4**.2? :(
2¢...

**Comment by paweldomas** [comment]
I'm sorry I gave it a try before doing that, but it's much bigger effort than it seems. This PR does not block from upgrade in future. To mention just a few problematic parts:
- all PacketExtension providers have to be refactored (this one is not very hard just manual work)
- I couldn't find JingleNodes equivalent (not sure if still used anywhere)
- SASL reworked
- some other classes used in so many operation sets we have were changed or missing 

It's possible that after migration some features would have to go away and some would probably end up broken.

https://github.com/igniterealtime/Smack/wiki/Smack-4.1-Readme-and-Upgrade-Guide

**Comment by paweldomas** [comment]
This branch contains our ongoing effort on first "compile" attempt:
https://github.com/paweldomas/jitsi/commits/local_smack4
Removed files were the things I couldn't port easily and was planning to work on adding them back after the compilation succeeds.

**Comment by ibauersachs** [comment]
I understand the reasons you did this, I was just ranting. Are aware of this [Smack 4 branch](https://github.com/jitsi/jitsi/tree/smack4)?

**Comment by paweldomas** [comment]
Yes my commit was done on top of that branch I pushed it to my repo as it's not very clean (more as experiment) didn't want to do a mess there.

**Pull request merged**
